import numpy as np
import pandas as pd

def atomicWeight(atoms):
    referAtom = []
    dict_Atomic_weight = {'Atom_H':1.008,
    'Atom_He':4.003,
    'Atom_Li':6.941,
    'Atom_Be':9.012,
    'Atom_B':10.81,
    'Atom_C':12.01,
    'Atom_N':14.01,
    'Atom_O':16.00,
    'Atom_F':19.00,
    'Atom_Ne':20.18,
    'Atom_Na':22.99,
    'Atom_Mg':24.31,
    'Atom_Al':26.98,
    'Atom_Si':28.09,
    'Atom_P':30.97,
    'Atom_S':32.07,
    'Atom_Cl':35.45,
    'Atom_Ar':26.98,
    'Atom_K':39.10,
    'Atom_Ca':40.08,
    'Atom_Sc':0,
    'Atom_Ti':0,
    'Atom_V':0,
    'Atom_Cr':0,
    'Atom_Mn':0,
    'Atom_Fe':0,
    'Atom_Co':0,
    'Atom_Ni':0,
    'Atom_Cu':0,
    'Atom_Zn':0,
    'Atom_Ga':0,
    'Atom_Ge':0,
    'Atom_As':0,
    'Atom_Se':0,
    'Atom_Br':0,
    'Atom_Kr':0,
    'Atom_Rb':0,
    'Atom_Sr':0,
    'Atom_Y':0,
    'Atom_Zr':0,
    'Atom_Nb':0,
    'Atom_Mo':0,
    'Atom_Tc':0,
    'Atom_Ru':0,
    'Atom_Rh':0,
    'Atom_Pd':0,
    'Atom_Ag':0,
    'Atom_Cd':0,
    'Atom_In':0,
    'Atom_Sn':0,
    'Atom_Sb':0,
    'Atom_Te':0,
    'Atom_I':0,
    'Atom_Xe':0,
    'Atom_Cs':0,
    'Atom_Ba':0,
    'Atom_La':0,
    'Atom_Ce':0,
    'Atom_Pr':0,
    'Atom_Nd':0,
    'Atom_Pm':0,
    'Atom_Sm':0,
    'Atom_Eu':0,
    'Atom_Gd':0,
    'Atom_Tb':0,
    'Atom_Dy':0,
    'Atom_Ho':0,
    'Atom_Er':0,
    'Atom_Tm':0,
    'Atom_Yb':0,
    'Atom_Lu':0,
    'Atom_Hb':0,
    'Atom_Ta':0,
    'Atom_W':0,
    'Atom_Re':0,
    'Atom_Os':0,
    'Atom_Ir':0,
    'Atom_Pt':0,
    'Atom_Au':197.0
    }
    referAtom = [dict_Atomic_weight[item] for item in atoms]
    return referAtom

if __name__ == "__main__":
    atoms = ['Atom_C', 'Atom_H', 'Atom_Mg', 'Atom_Cl']
    print(atomicWeight(atoms))
